# Crypto Parser Bot Configuration
# Chats for parsing crypto trader messages

settings:
  # Days to parse (today + yesterday = 2)
  parse_days: 2
  
  # Delay between parsing chats (seconds)
  request_delay_sec: 1.5
  
  # Minimum message length to include
  min_message_length: 10

chats:
  - "abtminerchat"
  - "AircoinGlobalChat"
  - "allminer_msk_chat"
  - "antmineropt"
  - "ApeXdex"
  - "aquaprotocolxyz"
  - "architec_ton"
  - "AtheneNetwork_Chat"
  - "bbqcoingroup8"
  - "BDGWIN_VIP_HUB00"
  - "beetongamechat"
  - "beincrypto_ru"
  - "belevskchat"
  - "bigcoin_BCX_community"
  - "billybob_chat"
  - "BinanceRussianSpeaking"
  - "bitpapa_com_chat_ru"
  - "blumcrypto_cis_chat"
  - "BybitRussian"
  - "chat_obmen_referal"
  - "CoinColaChat"
  - "Cryptan300Chat"
  - "cryptancichat"
  - "crypto_solyanka_squad"
  - "CryptoAv1t0"
  - "CryptoBotRussian"
  - "cryptocurrency_giveaways"
  - "cryptoemergencychat"
  - "CryptoFarmBitcoinChat"
  - "cryptoretarded"
  - "cryptoz_chat"
  - "cscalp"
  - "cscalp_crypto"
  - "decimalchain"
  - "DiaverseGame"
  - "DLchate"
  - "dropsearn_ru_chat"
  - "evadore"
  - "eywa_ru"
  - "FarmizenChat"
  - "gramilla_world_chat"
  - "GuildOTC"
  - "hamster_kombat_ruchat02"
  - "HTXRussian"
  - "incrypted_chat"
  - "irk_miners"
  - "krypto_baraholka"
  - "kucoin_binance1"
  - "kucoinrussianofficial"
  - "MagicNFTcollections"
  - "Maining_blockchain"
  - "mehtokenchat"
  - "mineinvest38"
  - "miningcenternet"
  - "NeurashiGP"
  - "nikicompanychat"
  - "notcoin_fam_ru"
  - "obmen_thb"
  - "obmenexc"
  - "okx_russian"
  - "osmiteckgroup"
  - "otcship"
  - "p2p_lab_chat"
  - "p2pdropi"
  - "pixelverse_xyz_cis"
  - "processing_russia"
  - "proton_chatroom"
  - "putincoinput"
  - "raysx_global_chat"
  - "ref_trade"
  - "referal_dlya_igr"
  - "referal_trade"
  - "reviewschatarrhiv1"
  - "Ric_mining"
  - "ROSSIARABOTA"
  - "RusCryptEx"
  - "satoshifriends"
  - "SCryptOTC"
  - "seregasoleniy"
  - "Shopmining1"
  - "stepnru"
  - "Swoptoky_exchange"
  - "TOMSolCoin_Chat"
  - "tonsocietycis"
  - "treydingfjf"
  - "trustpool"
  - "tutminers"
  - "VelesCommunityRu"
  - "VelesOfficialRu"
  - "virtualversionsrussian"
  - "walken_io"
  - "walken_io_ru"
  - "wallet_news_chat"
  - "web_investors"
  - "WeForGoldChat"
  - "wepad_ru"
  - "workua_2"
  - "xbotchatru"
  - "yobichatru"
  - "zarabotok_kriptovalyuty"
